name: paymentez
description: Paquete para agregar tarjetas en paymentez, sirve para proyectos que no tienen certificación PCI.
version: 1.0.0
author: Cristhian Hernandez <cristhian.hernandez@softnux.io>
homepage: https://github.com/Krysthyan/paymentez

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/html_paymentez2021/
